
const db=supabase.createClient(APP_CONFIG.SUPABASE_URL,APP_CONFIG.SUPABASE_KEY),el=id=>document.getElementById(id),esc=s=>String(s??"").replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function setMsg(t,ok=false){el("adminMsg").innerHTML=t?`<div class="notice ${ok?"success":"error"}">${esc(t)}</div>`:""}
async function isAdmin(){const{data,error}=await db.rpc("is_admin");return !error&&!!data}
async function show(){el("adminLogin").classList.add("hidden");el("panel").classList.remove("hidden");el("logoutBtn").classList.remove("hidden");await loadCodes()}
el("loginBtn").onclick=async()=>{const{error}=await db.auth.signInWithPassword({email:el("email").value.trim(),password:el("password").value});if(error)return el("loginMsg").innerHTML=`<div class="notice error">${esc(error.message)}</div>`;if(!(await isAdmin())){await db.auth.signOut();return el("loginMsg").innerHTML='<div class="notice error">Bu hesap yönetici değil.</div>'}await show()};
el("logoutBtn").onclick=async()=>{await db.auth.signOut();location.reload()};
async function loadCodes(){const{data,error}=await db.from("voters").select("id,code").order("id");if(error)return setMsg(error.message);el("codesWrap").innerHTML=data.length?`<table><tr><th>ID</th><th>Kod</th><th></th></tr>${data.map(r=>`<tr><td>${r.id}</td><td><code>${esc(r.code)}</code></td><td><button class="danger" onclick="deleteCode(${r.id})">Sil</button></td></tr>`).join("")}</table>`:'<div class="muted">Henüz kod yok.</div>'}
async function deleteCode(id){if(!confirm("Bu kod ve bu kişiye ait oylar silinsin mi?"))return;const{error}=await db.from("voters").delete().eq("id",id);if(error)return setMsg(error.message);await loadCodes()}
async function addCodes(codes){codes=[...new Set(codes.map(x=>x.trim()).filter(Boolean))];if(!codes.length)return;const{error}=await db.from("voters").insert(codes.map(code=>({code})));if(error)return setMsg(error.message);setMsg(`${codes.length} kod eklendi.`,true);await loadCodes()}
el("addCodeBtn").onclick=async()=>{await addCodes([el("singleCode").value]);el("singleCode").value=""};el("addBulkBtn").onclick=async()=>{await addCodes(el("bulkCodes").value.split(/\r?\n/));el("bulkCodes").value=""};el("refreshCodesBtn").onclick=loadCodes;
el("resetVotesBtn").onclick=async()=>{if(!confirm("Bütün oylar silinsin mi?"))return;const{error}=await db.from("votes").delete().gte("id",0);if(error)return setMsg(error.message);setMsg("Bütün oylar sıfırlandı.",true)};
function parseCSV(text){const rows=[];let row=[],cell="",q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'){if(q&&n==='"'){cell+='"';i++}else q=!q}else if(c===','&&!q){row.push(cell);cell=""}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(cell);cell="";if(row.some(v=>v.length))rows.push(row);row=[]}else cell+=c}row.push(cell);if(row.some(v=>v.length))rows.push(row);return rows}
function pick(h,pats){const l=h.map(x=>x.trim().toLowerCase());for(const p of pats){const i=l.findIndex(x=>x===p||x.includes(p));if(i>=0)return i}return-1}
el("replaceSongsBtn").onclick=async()=>{const f=el("csvFile").files[0];if(!f)return setMsg("Önce CSV seç.");if(!confirm("Eski şarkılar ve bütün oylar silinecek; öğrenci kodları kalacak. Devam?"))return;try{const rows=parseCSV(await f.text());if(rows.length<2)throw new Error("CSV boş.");const h=rows[0],it=pick(h,["title","song","name","video title"]),ia=pick(h,["artist","channel","uploader"]),im=pick(h,["thumbnail","image","cover"]),iu=pick(h,["url","link","video url"]);if(it<0)throw new Error("Şarkı adı sütunu bulunamadı.");const songs=rows.slice(1).map((r,i)=>({title:(r[it]||"").trim(),artist:ia>=0?(r[ia]||"").trim():"",thumbnail:im>=0?(r[im]||"").trim():"",youtube_url:iu>=0?(r[iu]||"").trim():"",original_order:i+1})).filter(s=>s.title);let res=await db.from("songs").delete().gte("id",0);if(res.error)throw res.error;const{error}=await db.from("songs").insert(songs);if(error)throw error;setMsg(`${songs.length} şarkı yüklendi.`,true)}catch(e){setMsg(e.message)}};
(async()=>{const{data}=await db.auth.getSession();if(data.session&&await isAdmin())await show()})();
